### ISSUE TITLE
Needs Reference To Actual 'require_relative' Import Statement

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-3-ruby-oo-inheritance-modules#11]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172694?module_item_id=376688

### Concern

This section needs the actual 'require_relative' statement to be more clear:

Note: remember to require the fancy_dance.rb file inside the dancer.rb and kid.rb, just like we did with our other file requirements.

### Suggested Changes

Changed Section:

Note: remember to require the fancy_dance.rb file inside the dancer.rb and kid.rb, just like we did with our other file requirements.

Inside 'dancer.rb' and 'kid.rb':
```
require_relative './fancy_dance.rb'
```

**Comment by lizbur10** [comment]
Hi @SamuelBanya - Given that the syntax of the command is exactly the same as what was provided earlier in the lesson, I don't think it's necessary to clarify further. Thanks as always for the suggestion 💙
