### ISSUE TITLE
Needs A Reference To The 'namespace resolution operator'

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-3-ruby-oo-inheritance-modules#12]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172694?module_item_id=376688

### Concern

This section needs to have a reference to the actual 'namespace resolution operator':

We refer to the namespaced modules or classes with ::

### Suggested Changes

Changed Section:

We refer to the namespaced modules or classes with '::', the 'namespace resolution operator'.

Reference:
- https://stackoverflow.com/questions/3009477/what-is-rubys-double-colon

**Comment by lizbur10** [comment]
Hi @SamuelBanya - the `::` operator is not specific to namespaces, so I think referring to it that way would be misleading. It's generally known as the 'constant resolution operator', but I don't think adding that would help clarify in this context.  

Thanks as always for contributing to the Flatiron School curriculum 💙
